
```{r}
library(dplyr)
library(data.table)
library(rmarkdown)


setwd("C:/Users/bryomill/Documents/R Files/UCI HAR Dataset")
subtest <- read.table("UCI HAR Dataset/test/subject_test.txt", col.names = "subject")
xtest <- read.table("UCI HAR Dataset/test/X_test.txt", col.names = features$functions)
ytest <- read.table("UCI HAR Dataset/test/y_test.txt", col.names = "code")
subtrain <- read.table("UCI HAR Dataset/train/subject_train.txt", col.names = "subject")
xtrain <- read.table("UCI HAR Dataset/train/X_train.txt", col.names = features$functions)
ytrain <- read.table("UCI HAR Dataset/train/y_train.txt", col.names = "code")
features <- read.table("UCI HAR Dataset/features.txt", col.names = c("n","functions"))
activities <- read.table("UCI HAR Dataset/activity_labels.txt", col.names = c("code", "activity"))

X <- rbind(x_train, x_test)
Y <- rbind(y_train, y_test)
Subject <- rbind(subject_train, subject_test)

MergeData <- cbind(Subject, Y, X)
Mean_Std.Extract <- MergeData %>% select(subject, code, contains("mean"), contains("std"))
Mean_Std.Extract$code <- activities[Mean_Std.Extract$code, 2]
names(Mean_Std.Extract)[2] = "activity"


names(Mean_Std.Extract)<-gsub("Acc", "Accelerometer", names(Mean_Std.Extract))
names(Mean_Std.Extract)<-gsub("Gyro", "Gyroscope", names(Mean_Std.Extract))
names(Mean_Std.Extract)<-gsub("BodyBody", "Body", names(Mean_Std.Extract))
names(Mean_Std.Extract)<-gsub("Mag", "Magnitude", names(Mean_Std.Extract))
names(Mean_Std.Extract)<-gsub("angle", "Angle", names(Mean_Std.Extract))
names(Mean_Std.Extract)<-gsub("gravity", "Gravity", names(Mean_Std.Extract))
names(Mean_Std.Extract)<-gsub("^t", "Time", names(Mean_Std.Extract))
names(Mean_Std.Extract)<-gsub("^f", "Frequency", names(Mean_Std.Extract))
names(Mean_Std.Extract)<-gsub("tBody", "TimeBody", names(Mean_Std.Extract))
names(Mean_Std.Extract)<-gsub("-mean()", "Mean", names(Mean_Std.Extract), ignore.case = TRUE)
names(Mean_Std.Extract)<-gsub("-std()", "STD", names(Mean_Std.Extract), ignore.case = TRUE)
names(Mean_Std.Extract)<-gsub("-freq()", "Frequency", names(Mean_Std.Extract), ignore.case = TRUE)


TidyData <- Mean_Std.Extract %>%
    group_by(subject, activity) %>%
    summarise_all(funs(mean))
write.table(TidyData, "TidyData.txt", row.name=FALSE)
